---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: maxim-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: 42 # latest is also supported if you want new updates ASAP

stages:
  - name: helix
    from: docker.io/library/rust:1.86
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git # Install git
          - git clone https://github.com/helix-editor/helix.git # Clone the helix repo
          - cd helix && rustup update stable && cargo +stable install --path helix-term # Use cargo to install
          - mkdir -p /out/ && mv $CARGO_HOME/bin/hx /out/hx && mv helix/runtime /out/ # Move bin and runtime

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install:
        - rpmfusion # install RPMFusion repos, including tainted repos & disable negativo17 repos if installed
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/kylegospo/webapp-manager/repo/fedora-%OS_VERSION%/kylegospo-webapp-manager-%OS_VERSION%.repo
    install:
      - syncthing
      - webapp-manager
      - fastfetch
      - fastfetch-fish-completion
      - fish
      - kitty
      - calibre
      - steam-devices # use if steam-flatpak
      # - steam
      # - mesa-va-drivers-freeworld
      # - mesa-vdpau-drivers-freeworld
      - gamescope
      - gamemode
      - gum
      - zathura
      - zathura-fish-completion
      - zathura-plugins-all
      - wqy-zenhei-fonts
      - ffmpeg
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      # - mesa-va-drivers
      # - mesa-vdpau-drivers

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - io.gitlab.librewolf-community
        - app.zen_browser.zen
        - com.discordapp.Discord
        - com.heroicgameslauncher.hgl
        - net.lutris.Lutris
        - com.vysp3r.ProtonPlus
        - org.keepassxc.KeePassXC
        - md.obsidian.Obsidian
        - app.polychromatic.controller
        - com.valvesoftware.Steam
        - com.github.tchx84.Flatseal
      remove:
        - org.mozilla.firefox
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages
  # - type: akmods
  #   base: main # if not specified, classic "main" base is used by default
  #   install:
  #     - openrazer
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    system:
      enabled:
        - syncthing@maxim.service

  # - type: brew
  #   nofile-limits: true # increase nofile limits
  #   brew-analytics: false # disable telemetry

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Inter
        - Victor Mono

  - type: copy
    from: helix
    src: /out/hx
    dest: /usr/bin/
  - type: copy
    from: helix
    src: /out/runtime
    dest: /usr/share/helix/

  - type: script
    snippets:
      - "sudo plymouth-set-default-theme catppuccin-mocha" # example: download binary

  - type: initramfs
