---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: maxim-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://openrazer.github.io/hardware:razer.repo
    install:
      - syncthing
      - starship
      - fish
      - kitty
      - bat
      - polychromatic
      - mesa-va-drivers-freeworld
      - mesa-vdpau-drivers-freeworld
      - gum
      - steam
      - zathura
      - zathura-fish-completion
      - zathura-plugins-all
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - mesa-va-drivers
      - mesa-vdpau-drivers

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - io.gitlab.librewolf-community
        - app.zen_browser.zen
        - com.discordapp.Discord
        - com.heroicgameslauncher.hgl
        - net.lutris.Lutris
        - com.vysp3r.ProtonPlus
        - org.keepassxc.KeePassXC
        - md.obsidian.Obsidian
      remove:
        - org.mozilla.firefox
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages
  - type: akmods
    base: main # if not specified, classic "main" base is used by default
    install:
      - openrazer
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    system:
      enabled:
        - syncthing@maxim.service

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: bling
    install:
      - rpmfusion # install RPMFusion repos, including tainted repos & disable negativo17 repos if installed
      - ublue-update # https://github.com/ublue-os/ublue-update

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Inter
        - Victor Mono
  - type: script
    snippets:
      - "sudo plymouth-set-default-theme -R catppuccin-mocha" # example: download binary
  - type: initramfs

stages:
  - name: bluebuild
    from: docker.io/library/rust:1.86
    modules: # same as the top-level modules key, but executed in the custom stage
      - type: script
        no-cache: true
        snippets:
          - cargo install --locked --all-features blue-build
